---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app-stage
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: git@github.com:sergiikotenko/gitops-webapp-demo.git
    targetRevision: HEAD
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-stage
  syncPolicy:
    automated:
      # If anything will be removed from the repo, than it will be authomatically removed from the cluster itself
      prune: true
      # If anything in k8s is diffenrent from the repo above, ArgoCD will rollback changes
      # and rollback to the state described in the GH config files
      selfHeal: true 
